"use client";
import { useEffect,useMemo,useState } from "react";
import { DataDragonIcon } from "@/components/live/DataDragonIcon";
import { DEFAULT_MISSION_SETTINGS } from "@/lib/mission/objective-config";
import { runMissionEngine } from "@/lib/mission/mission-engine";
import type { DuoCall,NormalizedGameData,SharedState } from "@/lib/realtime/types";
import { commanderFlashUsers } from "@/lib/commander/commander-utils";

const quickCalls=[["RESET","MID SS","SUPPORT SS","JUNGLE BOT","JUNGLE TOP","HOLD POSITION"],["PEEL ME","ENGAGE READY","NO FLASH ADC","DRAKE SETUP","BARON SETUP","HEIMER TURRETS READY"]];
const objectiveLabels={dragon:"DRACHE",grubs:"GRUBS",herald:"HERALD",baron:"BARON"};
const clock=(seconds:number)=>`${String(Math.floor(Math.max(0,seconds)/60)).padStart(2,"0")}:${String(Math.max(0,seconds)%60).padStart(2,"0")}`;

export function CommanderDeck({game,call,shared,botlaneEnemy,onCall,onShare,stale}:{code:string;game?:NormalizedGameData;call?:DuoCall;shared?:SharedState;botlaneEnemy:string[];onCall:(text:string)=>void;onShare:(state:SharedState)=>void;stale:boolean}){
  const [activeCall,setActiveCall]=useState(""),[now,setNow]=useState(Date.now());
  const connectorStatus=stale?"stale":game?"online":"offline";
  const output=useMemo(()=>game?runMissionEngine({gameId:game.gameId,gameTime:game.gameTime,gameMode:game.gameMode,mapName:game.mapName,connectorStatus,events:game.events,manualMission:call?{id:call.id,title:call.text,sourceName:call.source,createdAt:call.timestamp,acknowledged:call.acknowledgedBy.length>0}:undefined,overrides:shared?.missionEngine?.gameId===game.gameId?shared.missionEngine.overrides:{},settings:DEFAULT_MISSION_SETTINGS}):undefined,[call,game,shared?.missionEngine]);
  const mission=output?.mission,ownTeam=game?.activePlayer.team,enemies=game?.players.filter(player=>player.team!==ownTeam)??[],ordered=game?commanderFlashUsers(game,botlaneEnemy):[];
  const timers=shared?.timers??[];
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
  const startFlash=(index:number)=>{const id=["adc-flash","support-flash","mid-flash","jungle-flash"][index],existing=timers.find(timer=>timer.id===id);let seconds=300;if(existing?.running&&existing.targetTimestamp){const correction=window.prompt("Verbleibende Sekunden setzen (+30 / -30 oder Zielwert)",String(Math.max(0,Math.ceil((existing.targetTimestamp-Date.now())/1000))));if(correction===null)return;const current=Math.max(0,Math.ceil((existing.targetTimestamp-Date.now())/1000));seconds=correction==="+30"?current+30:correction==="-30"?Math.max(0,current-30):Number(correction);if(!Number.isFinite(seconds)||seconds<0)return}const next={id,targetTimestamp:Date.now()+seconds*1000,pausedRemaining:seconds*1000,running:seconds>0,updatedAt:Date.now(),sourceMemberId:"commander"},state:SharedState={timers:[...timers.filter(timer=>timer.id!==id),next],updatedAt:Date.now(),sourceMemberId:"commander"};onShare(state);setNow(Date.now())};
  const issue=(text:string)=>{setActiveCall(text);onCall(text);window.setTimeout(()=>setActiveCall(""),900)};
  const ours=game?.players.filter(player=>player.team===ownTeam&&["Nautilus","Heimerdinger"].includes(player.championName))??[],theirBot=botlaneEnemy.map(name=>enemies.find(player=>player.championName===name)).filter((player):player is NormalizedGameData["players"][number]=>Boolean(player));
  return <div className="commander-deck">
    <section className={`commander-mission severity-${mission?.severity??"calm"} ${stale?"is-stale":""}`}><div><span>{stale?"DATEN VERALTET":mission?.source==="manual"?`CALL VON ${call?.source.toUpperCase()}`:"AKTUELLE MISSION"}</span><h1>{mission?.title??"TEMPO"}</h1>{mission?.countdownSeconds!==undefined&&<b>{stale?"—":clock(mission.countdownSeconds)}</b>}</div><ul>{mission?.instructions.slice(0,4).map(item=><li key={item}>{item}</li>)}</ul>{call?.acknowledgedBy.length?<strong>✓ GS HAT VERSTANDEN</strong>:null}</section>
    <section className="commander-calls">{quickCalls.flat().map(text=><button key={text} className={activeCall===text?"active":call?.text===text&&!call.acknowledgedBy.length?"pending":call?.text===text&&call.acknowledgedBy.length?"confirmed":""} onClick={()=>issue(text)}>{text}</button>)}</section>
    <section className="commander-objectives"><span>OBJECTIVES</span>{output?.objectives.map(objective=><article key={objective.type} className={`${objective.status} ${mission?.type===objective.type?"important":""}`}><strong>{objectiveLabels[objective.type]}</strong><b>{stale?"NICHT AKTUELL":objective.countdownSeconds===undefined?objective.status.toUpperCase():clock(objective.countdownSeconds)}</b><em>{objective.status.toUpperCase()} · {objective.automatic?"AUTO":"MANUELL"}</em></article>)}</section>
    <section className="commander-flashes"><span>RELEVANTE FLASH-TIMER</span>{[0,1,2,3].map(index=>{const player=ordered[index],id=["adc-flash","support-flash","mid-flash","jungle-flash"][index],timer=timers.find(item=>item.id===id),remaining=timer?.running&&timer.targetTimestamp?Math.max(0,Math.ceil((timer.targetTimestamp-now)/1000)):0;return <button key={id} onClick={()=>startFlash(index)} className={index<2?"botlane":""}>{player?<DataDragonIcon type="champion" name={player.championName} size={54}/>:<span className="dd-fallback">?</span>}<strong>{player?.championName.toUpperCase()??["ADC","SUPPORT","MID","JUNGLE"][index]} FLASH</strong><b>{stale&&remaining?"NICHT AKTUELL":remaining?clock(remaining):"READY"}</b></button>})}</section>
    <section className="commander-botlane"><span>BOTLANE</span><div>{ours.map(player=><span key={player.championName}><DataDragonIcon type="champion" name={player.championName} size={38}/>{player.championName.toUpperCase()}</span>)}</div><b>VS</b><div>{theirBot.length?theirBot.map(player=><span key={player.championName}><DataDragonIcon type="champion" name={player.championName} size={38}/>{player.championName.toUpperCase()}</span>):<em>WIRD ERKANNT</em>}</div></section>
  </div>;
}
