"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { DEFAULT_MISSION_SETTINGS } from "@/lib/mission/objective-config";
import { runMissionEngine } from "@/lib/mission/mission-engine";
import type { AuthoritativeMatchState,DuoCall,MatchStateSource,NormalizedGameData,SessionMember,SharedState } from "@/lib/realtime/types";
import { useAudioUnlock } from "@/hooks/useAudioUnlock";
import { useScreenWakeLock } from "@/hooks/useScreenWakeLock";
import { useVibration } from "@/hooks/useVibration";
import { orderedEnemyRoster } from "@/lib/realtime/enemy-roster";
import { summonerTimerId } from "@/lib/summoners/summoner-timer-state";
type Status="online"|"stale"|"offline"|"ended";
const clock=(seconds:number)=>`${String(Math.floor(Math.max(0,seconds)/60)).padStart(2,"0")}:${String(Math.max(0,seconds)%60).padStart(2,"0")}`;
const displayTimerName=(id:string,game:NormalizedGameData|undefined,botlaneEnemy:string[])=>{for(const player of game?orderedEnemyRoster(game,botlaneEnemy):[]){const playerId=player.playerId||player.summonerName||player.championName;for(const spell of Object.values(player.summonerSpells))if(summonerTimerId(playerId,spell)===id)return`${player.championName} ${spell}`}return id.replaceAll("-"," ")};
export function CompanionView({code,call,game,shared,sessionState,matchState,matchSource,members,connectorStatus,connected,botlaneEnemy,onAck,onReconnect,onLeave}:{code:string;call?:DuoCall;game?:NormalizedGameData;shared?:SharedState["missionEngine"];sessionState?:SharedState;matchState:AuthoritativeMatchState;matchSource:MatchStateSource;members:SessionMember[];connectorStatus:Status;connected:boolean;botlaneEnemy:string[];onAck:()=>void;onReconnect:()=>void;onLeave:()=>void}){
  const audio=useAudioUnlock(),wake=useScreenWakeLock(),vibration=useVibration(),lastMission=useRef(""),[feedback,setFeedback]=useState(false);
  useEffect(()=>{if(process.env.NODE_ENV==="production")return;const debug=document.createElement("small");debug.className="companion-match-debug";debug.textContent=`CANONICAL MATCH STATE: sessionCode ${code} · gameId ${matchState.gameId??"–"} · gameTime ${matchState.gameTime??"–"} · phase ${matchState.phase} · connectorStatus ${matchState.connectorStatus} · updatedAt ${matchState.updatedAt??"–"} · enemyPlayerCount ${game?.enemyPlayers?.length??0} · source ${matchSource}`;document.body.appendChild(debug);return()=>debug.remove()},[code,game?.enemyPlayers?.length,matchSource,matchState]);
  const output=useMemo(()=>game?runMissionEngine({gameId:game.gameId,gameTime:game.gameTime,gameMode:game.gameMode,mapName:game.mapName,connectorStatus,events:game.events,manualMission:call?{id:call.id,title:call.text,sourceName:call.source,createdAt:call.timestamp,acknowledged:call.acknowledgedBy.length>0}:undefined,overrides:shared?.gameId===game.gameId?shared.overrides:{},settings:DEFAULT_MISSION_SETTINGS}):undefined,[call,connectorStatus,game,shared]),mission=output?.mission;
  useEffect(()=>{const button=document.createElement("button");button.className="companion-leave";button.textContent="SESSION VERLASSEN";button.addEventListener("click",onLeave);document.body.appendChild(button);return()=>button.remove()},[onLeave]);
  useEffect(()=>{if(!mission||lastMission.current===mission.id)return;lastMission.current=mission.id;const urgent=mission.severity==="urgent"||mission.severity==="live";audio.play(urgent);vibration.vibrate(urgent)},[audio,vibration,mission]);
  const acknowledge=()=>{onAck();setFeedback(true);window.setTimeout(()=>setFeedback(false),1200)};
  const fullscreen=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{}};
  const timers=(matchState.summonerTimers??sessionState?.timers??[]).filter(timer=>timer.running&&timer.targetTimestamp).slice(0,4).map(timer=>({...timer,id:displayTimerName(timer.id,game,botlaneEnemy)})),commanderOnline=members.some(member=>member.role==="support"),stale=connectorStatus==="stale";
  return <main className="companion"><header><div><span>GS COMPANION · SESSION {code}</span><h1>{!connected?"VERBINDUNG WIRD WIEDERHERGESTELLT":stale?"DATEN VERALTET":connectorStatus==="online"?"MATCH ERKANNT":"BEREIT"}</h1><p>COMMANDER {commanderOnline?"ONLINE":"OFFLINE"} · CONNECTOR {connectorStatus.toUpperCase()} · {game?`UPDATE ${Math.max(0,Math.round((Date.now()-new Date(game.updatedAt).getTime())/1000))}s`:"WARTE AUF DATEN"}</p></div><div className="companion-device-actions"><button disabled={audio.enabled} onClick={audio.unlock}>{audio.enabled?"TON AKTIV":"TON AKTIVIEREN"}</button><button onClick={fullscreen}>VOLLBILD</button><button disabled={wake.active||!wake.supported} onClick={wake.request}>{wake.active?"DISPLAY AKTIV":wake.supported?"DISPLAY AKTIV HALTEN":"WAKE LOCK NICHT VERFÜGBAR"}</button>{!connected&&<button onClick={onReconnect}>NEU VERBINDEN</button>}</div></header><div className="companion-grid"><section className={`companion-mission severity-${mission?.severity??"calm"}`}><span>{mission?.source==="manual"?`CALL VON ${call?.source.toUpperCase()} · ${new Date(call?.timestamp??0).toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})}`:"AKTUELLE MISSION"}</span><h2>{mission?.title??(game?"WARTE AUF MISSION":"WARTE AUF MATCH")}</h2>{mission?.countdownSeconds!==undefined&&<b>{clock(mission.countdownSeconds)}</b>}{mission?.instructions?.length?<ul>{mission.instructions.slice(0,3).map(item=><li key={item}>{item}</li>)}</ul>:null}{mission?.source==="manual"&&call&&!call.acknowledgedBy.length?<button className="companion-ack" onClick={acknowledge}>VERSTANDEN</button>:null}{(feedback||Boolean(call?.acknowledgedBy.length))&&mission?.source==="manual"?<strong>✓ VERSTANDEN</strong>:null}</section><aside className="companion-side"><section><span>NEXT OBJECTIVES</span>{output?.objectives.slice(0,4).map(objective=><div key={objective.type}><strong>{objective.type.toUpperCase()}</strong><b>{objective.countdownSeconds===undefined?objective.status.toUpperCase():clock(objective.countdownSeconds)}</b></div>)}</section><section><span>RELEVANTE TIMER</span>{timers.length?timers.map(timer=><div key={timer.id}><strong>{timer.id.replaceAll("-"," ").toUpperCase()}</strong><b>{clock(Math.ceil(((timer.targetTimestamp??Date.now())-Date.now())/1000))}</b></div>):<p>KEINE AKTIVEN TIMER</p>}</section><section><span>BOTLANE</span><b>{botlaneEnemy.filter(Boolean).join(" + ")||"WIRD ERKANNT"}</b></section></aside></div><footer><label>LAUTSTÄRKE <input type="range" min="0" max="1" step=".1" value={audio.volume} onChange={e=>audio.setVolume(Number(e.target.value))}/></label>{vibration.supported&&<label><input type="checkbox" checked={vibration.enabled} onChange={e=>vibration.setEnabled(e.target.checked)}/> VIBRATION</label>}<span>Querformat empfohlen · Zum Home-Bildschirm hinzufügen</span></footer></main>;
}
