"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import { MacroBoard } from "@/components/MacroBoard";
import { BotlanePanel } from "@/components/live/BotlanePanel";
import { ConnectorDebug } from "@/components/live/ConnectorDebug";
import { LiveMatchPanel } from "@/components/live/LiveMatchPanel";
import { TeamRoster } from "@/components/live/TeamRoster";
import { MissionEngineStatus } from "@/components/mission/MissionEngineStatus";
import { CompanionView } from "./CompanionView";
import { CompanionJoin } from "./CompanionJoin";
import { SessionOwnerTools } from "./SessionOwnerTools";
import { createSessionChannel } from "@/lib/realtime/session-channel";
import type { DuoCall,MemberRole,NormalizedGameData,SessionMember,SharedState } from "@/lib/realtime/types";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { createToken } from "@/lib/session-utils";
import { canPerformSessionAction,companionAcknowledgementState } from "@/lib/realtime/permissions";

const calls=["RESET","DRAKE SETUP","BARON SETUP","MID PUSH","HOLD POSITION","HEIMER TURRETS READY","HEIMER TURRETS NOT READY","PEEL ME","ENGAGE READY","NO FLASH ADC","MID SS","SUPPORT SS","JUNGLE TOP","JUNGLE BOT"];
const primaryCalls=["RESET","MID SS","SUPPORT SS","PEEL ME","ENGAGE READY","NO FLASH ADC","HOLD POSITION"];
type Identity={memberId:string;memberToken:string;displayName:string;role:MemberRole;companion?:boolean};

export function OnlineSession({code,mode}:{code:string;mode:"commander"|"companion"|"full"}){
  const [identity,setIdentity]=useState<Identity|null>(null),[loaded,setLoaded]=useState(false),[members,setMembers]=useState<SessionMember[]>([]),[call,setCall]=useState<DuoCall>(),[remoteState,setRemoteState]=useState<SharedState>(),[connected,setConnected]=useState(false),[game,setGame]=useState<NormalizedGameData>(),[secret,setSecret]=useState(""),[view,setView]=useState<"support"|"heimer"|"full">(mode==="full"?"full":"support"),[error,setError]=useState(""),[botlaneEnemy,setBotlaneEnemy]=useState<string[]>(["",""]);
  const companionToken="route-only";
  const channelRef=useRef<ReturnType<typeof createSessionChannel>|undefined>(undefined),persistTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  useEffect(()=>{try{const raw=localStorage.getItem(`macroboard-session-${code}`);if(raw){const stored=JSON.parse(raw) as Identity;setIdentity({...stored,companion:mode==="companion"})}setSecret(sessionStorage.getItem(`macroboard-connector-${code}`)??"")}catch{}finally{setLoaded(true)}},[code,mode]);
  const joinCompanion=async(displayName:string)=>{const client=getSupabaseBrowserClient();if(!client)throw new Error("Online-Modus ist nicht konfiguriert.");const {data:s}=await client.from("macroboard_sessions").select("id,expires_at").eq("code",code).maybeSingle();if(!s||new Date(s.expires_at).getTime()<Date.now())throw new Error("Session nicht gefunden oder abgelaufen.");const token=createToken();const {data:m,error:e}=await client.from("macroboard_members").insert({session_id:s.id,display_name:displayName,member_token:token,role:"heimer"}).select("id").single();if(e||!m)throw new Error(e?.message??"Beitritt fehlgeschlagen.");const next:Identity={memberId:m.id,memberToken:token,displayName,role:"heimer",companion:true};localStorage.setItem(`macroboard-session-${code}`,JSON.stringify(next));setIdentity(next)};
  const receive=useCallback((state:SharedState)=>{setRemoteState(state);if(state.call)setCall(state.call);if(state.botlaneEnemy)setBotlaneEnemy(state.botlaneEnemy)},[]);
  useEffect(()=>{const client=getSupabaseBrowserClient();if(!client||!identity)return;let alive=true;(async()=>{const {data:s}=await client.from("macroboard_sessions").select("id,expires_at,shared_state,game_data").eq("code",code).maybeSingle();if(!alive)return;if(!s){setError("Session nicht gefunden.");return}if(new Date(s.expires_at).getTime()<Date.now()){setError("Session abgelaufen.");return}const {data:m}=await client.from("macroboard_members").select("display_name,role").eq("id",identity.memberId).eq("member_token",identity.memberToken).maybeSingle();if(!m){setError("Companion-Link oder Mitgliedszugang ist ungültig.");return}const resolved:Identity={...identity,displayName:m.display_name,role:m.role as MemberRole};setIdentity(resolved);localStorage.setItem(`macroboard-session-${code}`,JSON.stringify(resolved));const initial=s.shared_state as SharedState;setRemoteState(initial);if(initial?.call)setCall(initial.call);if(initial?.botlaneEnemy)setBotlaneEnemy(initial.botlaneEnemy);if(s.game_data)setGame(s.game_data as NormalizedGameData);channelRef.current=createSessionChannel(client,code,{memberId:resolved.memberId,displayName:resolved.displayName,role:resolved.role,onlineAt:new Date().toISOString()},receive,setMembers);setConnected(true)})();const poll=window.setInterval(async()=>{const {data}=await client.from("macroboard_sessions").select("game_data,shared_state").eq("code",code).maybeSingle();if(data?.game_data)setGame(data.game_data as NormalizedGameData);if(data?.shared_state)receive(data.shared_state as SharedState)},3000);return()=>{alive=false;clearInterval(poll);channelRef.current?.close()}},[code,identity?.memberId,identity?.memberToken,receive]);
  const persist=useCallback(async(state:SharedState)=>{const client=getSupabaseBrowserClient();if(!client)return;const {data:s}=await client.from("macroboard_sessions").select("id,shared_state").eq("code",code).single();if(s)await client.from("macroboard_sessions").update({shared_state:{...(s.shared_state as object),...state},updated_at:new Date().toISOString()}).eq("id",s.id)},[code]);
  const send=async(text:string)=>{if(!identity||!canPerformSessionAction(identity.role,"send_call"))return;const next:DuoCall={id:crypto.randomUUID(),text,source:identity.displayName,sourceMemberId:identity.memberId,timestamp:Date.now(),acknowledgedBy:[]},state:SharedState={call:next,updatedAt:Date.now(),sourceMemberId:identity.memberId};setCall(next);await channelRef.current?.send(state);await persist(state)};
  const ack=async()=>{if(!call||!identity||!canPerformSessionAction(identity.role,"ack_call")||call.acknowledgedBy.includes(identity.displayName))return;const state=companionAcknowledgementState(call,identity.displayName,identity.memberId);setCall(state.call);await channelRef.current?.send(state);await persist(state)};
  const shareBoard=useCallback(async(state:SharedState)=>{if(!identity||!canPerformSessionAction(identity.role,"update_shared_state"))return;setRemoteState(state);await channelRef.current?.send(state);clearTimeout(persistTimer.current);persistTimer.current=setTimeout(()=>void persist(state),700)},[identity,persist]);
  const gameAge=game?.updatedAt?Math.max(0,Math.round((Date.now()-new Date(game.updatedAt).getTime())/1000)):0,gameStatus=(game as NormalizedGameData&{status?:string}|undefined)?.status,liveStatus:"waiting"|"online"|"stale"|"ended"=gameStatus==="ended"?"ended":!game?"waiting":gameAge>10?"stale":"online",connectorStatus=liveStatus==="waiting"?"offline":liveStatus;
  const changeBotlane=(next:string[])=>{setBotlaneEnemy(next);if(identity)void shareBoard({botlaneEnemy:next,updatedAt:Date.now(),sourceMemberId:identity.memberId})};
  if(error)return <main className="min-h-screen grid place-items-center bg-black text-center"><div><h1 className="text-3xl font-black text-red-400">{error}</h1><a href="/" className="mt-5 inline-block text-fuchsia-400">Zurück zum Board</a></div></main>;
  if(!loaded)return <main className="min-h-screen grid place-items-center bg-black font-black">VERBINDUNG WIRD HERGESTELLT…</main>;
  if(!identity&&mode==="companion")return <CompanionJoin code={code} onJoin={joinCompanion}/>;
  if(!identity)return <main className="min-h-screen grid place-items-center bg-black"><div className="panel p-8 text-center"><h1 className="text-2xl font-black">Beitritt erforderlich</h1><a href="/" className="mt-5 inline-block text-fuchsia-400">Lobby öffnen</a></div></main>;
  if(mode==="companion")return <CompanionView code={code} call={call} game={game} shared={remoteState?.missionEngine} sessionState={remoteState} members={members} connectorStatus={connectorStatus} connected={connected} botlaneEnemy={botlaneEnemy} onAck={ack} onReconnect={()=>location.reload()}/>;
  return <div className={`online-session view-${view}`}>{secret&&companionToken&&<SessionOwnerTools code={code} connectorSecret={secret} companionToken={companionToken}/>}<section className="online-command"><div><span className="text-xs font-black tracking-[.25em] text-emerald-400">SESSION {code}</span><h1 className="text-xl font-black">{identity.displayName}</h1></div><div className="online-badges"><span>SUPABASE {connected?"ONLINE":"OFFLINE"}</span><span>PARTNER {members.length>1?"ONLINE":"WARTET"}</span><span>CONNECTOR {liveStatus==="online"?"ONLINE":liveStatus==="stale"?"VERALTET":"OFFLINE"}</span><span>MATCH {liveStatus==="ended"?"BEENDET":game?"ERKANNT":"WARTET"}</span>{game&&<span>UPDATE {gameAge}s</span>}</div></section><div className="live-dashboard"><MissionEngineStatus game={game} connectorStatus={connectorStatus} call={call} shared={remoteState?.missionEngine} sourceMemberId={identity.memberId} onShare={shareBoard} onAck={ack}/><div className="engine-quick-calls">{primaryCalls.map(x=><button disabled={identity.role==="spectator"} key={x} onClick={()=>send(x)}>{x}</button>)}</div><LiveMatchPanel game={game} age={gameAge} status={liveStatus}/>{game&&liveStatus!=="ended"&&<><BotlanePanel game={game} enemies={botlaneEnemy} onChange={changeBotlane} disabled={identity.role==="spectator"}/><TeamRoster game={game} view={view}/></>}{view==="full"&&<ConnectorDebug game={game}/>}</div><section className="online-tools"><div className="flex flex-wrap gap-2"><strong className="mr-2 py-2">ANSICHT</strong>{(["support","heimer","full"] as const).map(v=><button key={v} onClick={()=>setView(v)} className={view===v?"active":""}>{v==="full"?"VOLLANSICHT":v.toUpperCase()}</button>)}</div><div className="presence-list">{members.map(m=><span key={m.memberId}><i/> {m.displayName} · {m.role.toUpperCase()} ONLINE</span>)}</div><div className="duo-calls secondary-calls">{calls.filter(x=>!primaryCalls.includes(x)).map(x=><button disabled={identity.role==="spectator"} key={x} onClick={()=>send(x)}>{x}</button>)}</div></section><MacroBoard relevantSummoners={botlaneEnemy.filter(Boolean)} liveGame={game} remoteState={remoteState} onSharedState={shareBoard} sourceMemberId={identity.memberId} readOnly={identity.role==="spectator"}/></div>;
}
