"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { MacroBoard } from "@/components/MacroBoard";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { createSessionChannel } from "@/lib/realtime/session-channel";
import type { DuoCall, MemberRole, NormalizedGameData, SessionMember, SharedState } from "@/lib/realtime/types";
import { LiveMatchPanel } from "@/components/live/LiveMatchPanel";
import { TeamRoster } from "@/components/live/TeamRoster";
import { BotlanePanel } from "@/components/live/BotlanePanel";
import { ConnectorDebug } from "@/components/live/ConnectorDebug";
import { MissionEngineStatus } from "@/components/mission/MissionEngineStatus";

const calls=["RESET","DRAKE SETUP","BARON SETUP","MID PUSH","HOLD POSITION","HEIMER TURRETS READY","HEIMER TURRETS NOT READY","PEEL ME","ENGAGE READY","NO FLASH ADC","MID SS","JUNGLE TOP","JUNGLE BOT"];
const primaryCalls=["RESET","MID SS","PEEL ME","ENGAGE READY","NO FLASH ADC","HOLD POSITION"];
type Identity={memberId:string;memberToken:string;displayName:string;role:MemberRole};
export function OnlineSession({code}:{code:string}){
  const [identity,setIdentity]=useState<Identity|null>(null);const [members,setMembers]=useState<SessionMember[]>([]);const [call,setCall]=useState<DuoCall>();const [remoteState,setRemoteState]=useState<SharedState>();const [connected,setConnected]=useState(false);const [game,setGame]=useState<NormalizedGameData>();const [secret,setSecret]=useState("");const [view,setView]=useState<"support"|"heimer"|"full">("full");const [error,setError]=useState("");const [botlaneEnemy,setBotlaneEnemy]=useState<string[]>(["",""]);const channelRef=useRef<ReturnType<typeof createSessionChannel>|undefined>(undefined);const persistTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  useEffect(()=>{try{const raw=localStorage.getItem(`macroboard-session-${code}`);if(raw)setIdentity(JSON.parse(raw));setSecret(sessionStorage.getItem(`macroboard-connector-${code}`)??"")}catch{}},[code]);
  const receive=useCallback((state:SharedState)=>{setRemoteState(state);if(state.call)setCall(state.call);if(state.botlaneEnemy)setBotlaneEnemy(state.botlaneEnemy)},[]);
  useEffect(()=>{const client=getSupabaseBrowserClient();if(!client||!identity)return;let alive=true;(async()=>{const {data:s}=await client.from("macroboard_sessions").select("id,expires_at,shared_state,game_data").eq("code",code).maybeSingle();if(!alive)return;if(!s){setError("Session nicht gefunden.");return}if(new Date(s.expires_at).getTime()<Date.now()){setError("Session abgelaufen.");return}const {data:storedMember}=await client.from("macroboard_members").select("display_name,role").eq("id",identity.memberId).eq("member_token",identity.memberToken).maybeSingle();const resolved:Identity=storedMember?{...identity,displayName:storedMember.display_name,role:storedMember.role as MemberRole}:identity;if(storedMember){setIdentity(resolved);localStorage.setItem(`macroboard-session-${code}`,JSON.stringify(resolved))}const initial=s.shared_state as SharedState;if(initial?.call)setCall(initial.call);if(initial?.botlaneEnemy)setBotlaneEnemy(initial.botlaneEnemy);if(s.game_data)setGame(s.game_data as NormalizedGameData);const member:SessionMember={memberId:resolved.memberId,displayName:resolved.displayName,role:resolved.role,onlineAt:new Date().toISOString()};channelRef.current=createSessionChannel(client,code,member,receive,setMembers);setConnected(true)})();const poll=window.setInterval(async()=>{const {data}=await client.from("macroboard_sessions").select("game_data").eq("code",code).maybeSingle();if(data?.game_data)setGame(data.game_data as NormalizedGameData)},3000);return()=>{alive=false;clearInterval(poll);channelRef.current?.close()}},[code,identity?.memberId,identity?.memberToken,receive]);
  const send=async(text:string)=>{if(!identity||identity.role==="spectator")return;const next:DuoCall={id:crypto.randomUUID(),text,source:identity.displayName,sourceMemberId:identity.memberId,timestamp:Date.now(),acknowledgedBy:[]};setCall(next);const state:SharedState={call:next,updatedAt:Date.now(),sourceMemberId:identity.memberId};await channelRef.current?.send(state);const client=getSupabaseBrowserClient();if(client){const {data:s}=await client.from("macroboard_sessions").select("id,shared_state").eq("code",code).single();if(s)await client.from("macroboard_sessions").update({shared_state:{...(s.shared_state as object),...state},updated_at:new Date().toISOString()}).eq("id",s.id)}};
  const ack=async()=>{if(!call||!identity||call.acknowledgedBy.includes(identity.displayName))return;const next={...call,acknowledgedBy:[...call.acknowledgedBy,identity.displayName]};setCall(next);await channelRef.current?.send({call:next,updatedAt:Date.now(),sourceMemberId:identity.memberId})};
  const shareBoard=useCallback(async(state:SharedState)=>{setRemoteState(state);await channelRef.current?.send(state);clearTimeout(persistTimer.current);persistTimer.current=setTimeout(async()=>{const client=getSupabaseBrowserClient();if(!client)return;const {data:s}=await client.from("macroboard_sessions").select("id,shared_state").eq("code",code).single();if(s)await client.from("macroboard_sessions").update({shared_state:{...(s.shared_state as object),...state},updated_at:new Date().toISOString()}).eq("id",s.id)},700)},[code]);
  const copy=(value:string)=>navigator.clipboard.writeText(value);
  const gameAge=game?.updatedAt?Math.max(0,Math.round((Date.now()-new Date(game.updatedAt).getTime())/1000)):0;const gameStatus=(game as NormalizedGameData&{status?:string}|undefined)?.status;const liveStatus: "waiting"|"online"|"stale"|"ended"=gameStatus==="ended"?"ended":!game?"waiting":gameAge>10?"stale":"online";
  const changeBotlane=(next:string[])=>{setBotlaneEnemy(next);if(identity)shareBoard({botlaneEnemy:next,updatedAt:Date.now(),sourceMemberId:identity.memberId})};
  if(error)return <main className="min-h-screen grid place-items-center bg-black text-center"><div><h1 className="text-3xl font-black text-red-400">{error}</h1><a href="/" className="mt-5 inline-block text-fuchsia-400">Zurück zum lokalen Board</a></div></main>;
  if(!identity)return <main className="min-h-screen grid place-items-center bg-black"><div className="panel p-8 text-center"><h1 className="text-2xl font-black">Beitritt erforderlich</h1><p className="mt-2 text-zinc-400">Bitte über die Lobby beitreten.</p><a href="/" className="mt-5 inline-block rounded-xl bg-fuchsia-600 px-5 py-3 font-bold">Lobby öffnen</a></div></main>;
  return <div className={`online-session view-${view}`}><section className="online-command"><div><span className="text-xs font-black tracking-[.25em] text-emerald-400">SESSION {code}</span><h1 className="text-xl font-black">{identity.displayName}</h1></div><div className="online-badges"><span>SUPABASE {connected?"ONLINE":"OFFLINE"}</span><span>PARTNER {members.length>1?"ONLINE":"WARTET"}</span><span>CONNECTOR {liveStatus==="online"?"ONLINE":liveStatus==="stale"?"VERALTET":"OFFLINE"}</span><span>MATCH {liveStatus==="ended"?"BEENDET":game?"ERKANNT":"WARTET"}</span>{game&&<span>UPDATE {gameAge}s</span>}</div><div className="flex gap-2"><button onClick={()=>copy(location.href)}>LINK</button>{secret&&<button onClick={()=>copy(secret)}>CONNECTOR</button>}</div></section><div className="live-dashboard"><MissionEngineStatus game={game} connectorStatus={liveStatus==="online"?"online":liveStatus==="stale"?"stale":liveStatus==="ended"?"ended":"offline"} call={call} shared={remoteState?.missionEngine} sourceMemberId={identity.memberId} onShare={shareBoard} onAck={ack}/><div className="engine-quick-calls">{primaryCalls.map(x=><button disabled={identity.role==="spectator"} key={x} onClick={()=>send(x)}>{x}</button>)}</div><LiveMatchPanel game={game} age={gameAge} status={liveStatus}/>{game&&liveStatus!=="ended"&&<><BotlanePanel game={game} enemies={botlaneEnemy} onChange={changeBotlane} disabled={identity.role==="spectator"}/><TeamRoster game={game} view={view}/></>} {view==="full"&&<ConnectorDebug game={game}/>}</div><section className="online-tools"><div className="flex flex-wrap gap-2"><strong className="mr-2 py-2">ANSICHT</strong>{(["support","heimer","full"] as const).map(v=><button key={v} onClick={()=>setView(v)} className={view===v?"active":""}>{v==="full"?"VOLLANSICHT":v.toUpperCase()}</button>)}</div><div className="presence-list">{members.map(m=><span key={m.memberId}><i/> {m.displayName} · {m.role.toUpperCase()} ONLINE</span>)}</div><div className="duo-calls secondary-calls">{calls.filter(x=>!primaryCalls.includes(x)).map(x=><button disabled={identity.role==="spectator"} key={x} onClick={()=>send(x)}>{x}</button>)}</div></section><MacroBoard relevantSummoners={botlaneEnemy.filter(Boolean)} liveGame={game} remoteState={remoteState} onSharedState={shareBoard} sourceMemberId={identity.memberId} readOnly={identity.role==="spectator"} /></div>;
}
